trigger:
 branches:
  include:
     - main
 paths:
  include:
   - SCSC.Core
   - SCSC.APIClient
   - SCSC.AdminWeb

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    pool:
      vmImage: $(vmImage)

    steps:
    - task: DotNetCoreCLI@2
      name: RestoreCoreComponent
      displayName: 'Restore SCSC.Core references'
      inputs:
        command: 'restore'
        projects: 'SCSC.Core/SCSC.Core.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      name: BuildCoreComponent
      displayName: 'Build SCSC.Core project'
      inputs:
        command: 'build'
        projects: 'SCSC.Core/SCSC.Core.csproj'

    - task: DotNetCoreCLI@2
      name: BuildCoreTests
      displayName: 'Build SCSC.Core.Test project'
      inputs:
        command: 'build'
        projects: 'Tests/SCSC.Core.Test/SCSC.Core.Test.csproj'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          Tests\**\*SCSC.Core.Test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: DotNetCoreCLI@2
      name: RestoreAPIClientComponent
      displayName: 'Restore SCSC.APIClient references'
      inputs:
        command: 'restore'
        projects: 'SCSC.APIClient/SCSC.APIClient.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      name: BuildAPIClientComponent
      displayName: 'Build SCSC.APIClient project'
      inputs:
        command: 'build'
        projects: 'SCSC.APIClient/SCSC.APIClient.csproj'

    - task: DotNetCoreCLI@2
      name: RestoreAdminWeb
      displayName: 'Restore SCSC.AdminWeb references'
      inputs:
        command: 'restore'
        projects: 'SCSC.AdminWeb/SCSC.AdminWeb.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      name: BuildAdminWeb
      displayName: 'Build SCSC.AdminWeb project'
      inputs:
        command: 'build'
        projects: 'SCSC.AdminWeb/SCSC.AdminWeb.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish SCSC.AdminWeb project'
      inputs:
        command: 'publish'
        projects: 'SCSC.AdminWeb/SCSC.AdminWeb.csproj'
        publishWebProjects: False
        arguments: '--output $(Build.StagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'adminWeb'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
    - job: DeployAdminWebToAzure
      displayName: 'Deploy Admin Web Site to Azure'
      pool:
        vmImage: $(vmImage)

      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'adminWeb'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Visual Studio Enterprise (2) Connection'
          appType: 'webApp'
          WebAppName: 'scscdemoadmin'
          packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'